// Admin surface copy — bilingual (FR primary, EN toggle).
//
// Same pattern as the landing text.ts: define fr first, derive the shape,
// then declare LANDING_TEXT keyed by Lang so TypeScript catches missing
// EN strings at compile time.

export type Lang = 'fr' | 'en'

const fr = {
  // Shell
  shellBrand: 'Win & Win',
  shellSuperAdmin: 'Super Admin',
  shellSectionNavigation: 'Navigation',
  shellNavOverview: 'Aperçu',
  shellNavMerchants: 'Commerçants',
  shellNavContacts: 'Contacts',
  shellNavSettings: 'Paramètres',
  shellBackToDashboard: 'Retour au tableau de bord',
  shellSignOut: 'Se déconnecter',
  shellSuperAdminLabel: 'Super Admin',

  // Common
  commonLoading: 'Chargement…',
  commonRefresh: 'Rafraîchir',
  commonApiOffline: 'API hors ligne',
  commonRetry: 'Réessayer',
  commonCancel: 'Annuler',
  commonSave: 'Enregistrer',
  commonSaving: 'Enregistrement…',
  commonSaved: 'Enregistré',
  commonViewAll: 'Voir tout',
  commonProcessing: 'Traitement en cours…',
  commonNotFound: 'Introuvable',
  commonUnauthorized: 'Non autorisé',
  commonUnknownError: 'Une erreur est survenue',

  // Overview
  overviewTitle: 'Aperçu',
  overviewKpiMerchants: 'Commerçants',
  overviewKpiPlayers: 'Joueurs',
  overviewKpiGamesToday: 'Parties (aujourd\'hui)',
  overviewKpiCoupons: 'Coupons',
  overviewKpiGamesThisMonth: 'Parties (ce mois)',
  overviewKpiNewThisWeek: 'Nouveaux cette semaine',
  overviewKpiDisabled: 'Désactivés',
  overviewTopMerchants: 'Top commerçants',
  overviewTopMerchantsEmpty: 'Aucune activité commerçant enregistrée pour le moment.',
  overviewColRank: 'Rang',
  overviewColName: 'Nom',
  overviewColPlays: 'Parties',
  overviewRecentContacts: 'Contacts récents',
  overviewRecentContactsEmpty: 'Aucune demande de contact pour le moment.',
  overviewRecentActivity: 'Activité récente',
  overviewRecentActivityEmpty: 'Aucune activité récente.',
  overviewColMerchant: 'Commerçant',
  overviewColResult: 'Résultat',
  overviewColTime: 'Heure',

  // Merchants list
  merchantsTitle: 'Commerçants',
  merchantsCountOne: 'commerçant trouvé',
  merchantsCountMany: 'commerçants trouvés',
  merchantsSearchPlaceholder: 'Rechercher un commerçant par nom ou email…',
  merchantsColName: 'Nom',
  merchantsColCategory: 'Catégorie',
  merchantsColTier: 'Plan',
  merchantsColStatus: 'Statut',
  merchantsColMonthlyPlays: 'Parties (mois)',
  merchantsColUsage: 'Utilisation',
  merchantsColJoined: 'Inscription',
  merchantsStatusActive: 'Actif',
  merchantsStatusDisabled: 'Désactivé',
  merchantsToggleEnable: 'Activer le commerçant',
  merchantsToggleDisable: 'Désactiver le commerçant',
  merchantsUsageAtLimit: 'Plafond atteint',
  merchantsEmpty: 'Aucun commerçant trouvé.',
  merchantsErrorLoad: 'Impossible de charger les commerçants.',

  // Merchant detail
  merchantDetailBack: 'Commerçants',
  merchantDetailStatActive: 'Actif',
  merchantDetailSlug: 'Slug',
  merchantDetailCreated: 'Créé',
  merchantDetailDisabledBannerTitle: 'Ce commerçant est désactivé',
  merchantDetailDisabledBannerBody:
    'Les joueurs ne peuvent plus accéder à la page de jeu. Le commerçant voit un écran « Jeu indisponible ».',
  merchantDetailEnableButton: 'Activer le commerçant',
  merchantDetailEnabling: 'Activation…',
  merchantDetailDisableButton: 'Désactiver le commerçant',
  merchantDetailDisabling: 'Désactivation…',
  merchantDetailViewPlayerPage: 'Voir la page joueur',
  merchantDetailResetPlays: 'Réinitialiser les parties du mois',
  merchantDetailDelete: 'Supprimer le commerçant',
  merchantDetailFeedbackEnabled: 'Commerçant activé',
  merchantDetailFeedbackDisabled: 'Commerçant désactivé',
  merchantDetailFeedbackUpdateFail: 'Échec de la mise à jour',
  merchantDetailFeedbackResetOk: 'parties réinitialisées pour ce mois',
  merchantDetailFeedbackResetFail: 'Échec de la réinitialisation',
  merchantDetailFeedbackDeleteFail: 'Échec de la suppression',
  merchantDetailNotFound: 'Commerçant introuvable',
  merchantDetailLoadFail: 'Impossible de charger le commerçant',
  merchantDetailResetConfirmTitle: 'Réinitialiser les parties du mois',
  merchantDetailResetConfirmBody:
    'Ceci supprime définitivement toutes les parties de ce commerçant sur le mois en cours. Action irréversible.',
  merchantDetailResetConfirmButton: 'Réinitialiser',
  merchantDetailDeleteConfirmTitle: 'Supprimer le commerçant',
  merchantDetailDeleteConfirmBody:
    'Ceci supprime définitivement le commerçant et TOUTES ses données (jeux, joueurs, coupons, parties). Action irréversible.',
  merchantDetailDeleteConfirmButton: 'Supprimer définitivement',
  merchantDetailUsageTitle: 'Utilisation mensuelle',
  merchantDetailUsagePlaysUnit: 'parties',
  merchantDetailUsageUnlimited: 'Illimité',
  merchantDetailUsageUnlimitedNote: 'Plan illimité — aucun plafond',
  merchantDetailUsagePercentUsed: '% du plafond mensuel utilisé',
  merchantDetailStatTotalPlayers: 'Joueurs totaux',
  merchantDetailStatTotalGames: 'Jeux totaux',
  merchantDetailStatActiveGames: 'Jeux actifs',
  merchantDetailStatCouponsRedeemed: 'Coupons validés',
  merchantDetailGamesTitle: 'Jeux',
  merchantDetailGamesEmpty: 'Aucun jeu configuré pour le moment.',
  merchantDetailPlayersTitle: 'Joueurs',
  merchantDetailPlayersEmpty: 'Aucun joueur pour le moment.',
  merchantDetailPlayersShowingOf: 'sur',
  merchantDetailPlayersShowingSuffix: 'joueurs affichés',
  merchantDetailCouponsTitle: 'Coupons récents',
  merchantDetailCouponsEmpty: 'Aucun coupon généré pour le moment.',
  merchantDetailColType: 'Type',
  merchantDetailColCreated: 'Créé',
  merchantDetailColLastSeen: 'Vu pour la dernière fois',
  merchantDetailColCode: 'Code',
  merchantDetailColPrize: 'Prix',
  merchantDetailColValidUntil: 'Valide jusqu\'au',
  merchantDetailPlayerAnonymous: 'Anonyme',
  merchantDetailColPlays: 'Parties',
  merchantDetailColWins: 'Gains',
  merchantDetailColEmail: 'Email',

  // Tier changer
  tierChangerLabel: 'Plan :',
  tierChangerSave: 'Enregistrer',
  tierChangerConfirmChange: 'Confirmer le changement',
  tierChangerConfirming: 'Confirmation…',
  tierChangerCancel: 'Annuler',
  tierChangerConfirmPrefix: 'Êtes-vous sûr ? Le plan passera de',
  tierChangerConfirmTo: 'à',

  // Contacts
  contactsTitle: 'Demandes de contact',
  contactsErrorLoad: 'Erreur de chargement',
  contactsTotalSuffix: 'au total',
  contactsColDate: 'Date',
  contactsColBusiness: 'Entreprise',
  contactsColContact: 'Contact',
  contactsColEmail: 'Email',
  contactsColPhone: 'Téléphone',
  contactsColType: 'Type',
  contactsColStatus: 'Statut',
  contactsEmpty: 'Aucune demande de contact pour le moment.',
  contactsStatusNew: 'Nouveau',
  contactsStatusContacted: 'Contacté',
  contactsStatusConverted: 'Converti',
  contactsStatusRejected: 'Rejeté',
  contactsMessageLabel: 'Message :',

  // Settings
  settingsTitle: 'Paramètres de la plateforme',
  settingsSubtitle: 'Configurez les plafonds par plan et les paramètres globaux.',
  settingsFeedbackTierSaved: 'Plafonds par plan enregistrés avec succès',
  settingsFeedbackPlatformSaved: 'Paramètres de la plateforme enregistrés avec succès',
  settingsFeedbackTierFail: 'Échec de l\'enregistrement des plafonds',
  settingsFeedbackPlatformFail: 'Échec de l\'enregistrement des paramètres',
  settingsTierSectionTitle: 'Plafonds par plan',
  settingsTierSectionSource: 'Source :',
  settingsTierSectionSourceDb: 'Base de données',
  settingsTierSectionSourceDefault: 'Défaut (pas de valeurs en base)',
  settingsTierSaveButton: 'Enregistrer les plafonds',
  settingsTierMonthlyPlays: 'Plafond de parties mensuelles',
  settingsPlatformSectionTitle: 'Paramètres de la plateforme',
  settingsPlatformSectionSubtitle: 'Configuration globale de la plateforme.',
  settingsPlatformSaveButton: 'Enregistrer les paramètres',
  settingsPlatformDefaultAtmosphere: 'Ambiance par défaut des nouveaux commerçants',
  settingsPlatformAtmosphereHelp: 'Appliquée aux nouveaux commerçants à leur inscription.',
  settingsPlatformSiteName: 'Nom du site',
  settingsPlatformSupportEmail: 'Email de support',
  settingsSourceInfoTitle: 'Configuration en base de données',
  settingsSourceInfoBody:
    'Tous les paramètres sont stockés dans la table platform_settings. Les modifications prennent effet dans les 30 secondes. Les valeurs par défaut ne s\'appliquent que si aucune valeur n\'existe en base.',

  // Public sign-up toggle
  settingsSignupSectionTitle: 'Essayez l\'application',
  settingsSignupSectionSubtitle:
    'Contrôlez si les visiteurs peuvent créer un compte eux-mêmes.',
  settingsSignupToggleLabel: 'Inscription publique',
  settingsSignupToggleDescOn:
    'Activée — les visiteurs peuvent créer un compte via /sign-up (email/mot de passe ou Google).',
  settingsSignupToggleDescOff:
    'Désactivée — la page /sign-up affiche un message de contact (WhatsApp + formulaire). Vous créez les comptes manuellement.',
  settingsSignupFeedbackSaved: 'Statut enregistré',
  settingsSignupFeedbackFail: 'Échec de l\'enregistrement du statut',
  settingsSignupBadgeOn: 'Activée',
  settingsSignupBadgeOff: 'Désactivée',

  // Atmospheres (select options)
  atmosphereJoyful: 'Joyeux',
  atmosphereElegant: 'Élégant',
  atmosphereEnergetic: 'Énergique',
  atmosphereCalm: 'Calme',
  atmosphereFestive: 'Festif',
  atmosphereLuxury: 'Luxueux',
  atmospherePlayful: 'Ludique',
  atmosphereNeon: 'Néon',
  atmosphereCustom: 'Personnalisé',

  // Tier labels (select options)
  tierFree: 'Gratuit',
  tierStarter: 'Starter',
  tierPro: 'Pro',
  tierEnterprise: 'Entreprise',
}

export type AdminText = typeof fr

const en: AdminText = {
  shellBrand: 'Win & Win',
  shellSuperAdmin: 'Super Admin',
  shellSectionNavigation: 'Navigation',
  shellNavOverview: 'Overview',
  shellNavMerchants: 'Merchants',
  shellNavContacts: 'Contacts',
  shellNavSettings: 'Settings',
  shellBackToDashboard: 'Back to Dashboard',
  shellSignOut: 'Sign Out',
  shellSuperAdminLabel: 'Super Admin',

  commonLoading: 'Loading…',
  commonRefresh: 'Refresh',
  commonApiOffline: 'API offline',
  commonRetry: 'Retry',
  commonCancel: 'Cancel',
  commonSave: 'Save',
  commonSaving: 'Saving…',
  commonSaved: 'Saved',
  commonViewAll: 'View all',
  commonProcessing: 'Processing…',
  commonNotFound: 'Not found',
  commonUnauthorized: 'Unauthorized',
  commonUnknownError: 'Something went wrong',

  overviewTitle: 'Overview',
  overviewKpiMerchants: 'Merchants',
  overviewKpiPlayers: 'Players',
  overviewKpiGamesToday: 'Games (today)',
  overviewKpiCoupons: 'Coupons',
  overviewKpiGamesThisMonth: 'Games (this month)',
  overviewKpiNewThisWeek: 'New this week',
  overviewKpiDisabled: 'Disabled',
  overviewTopMerchants: 'Top merchants',
  overviewTopMerchantsEmpty: 'No merchant activity recorded yet.',
  overviewColRank: 'Rank',
  overviewColName: 'Name',
  overviewColPlays: 'Plays',
  overviewRecentContacts: 'Recent contacts',
  overviewRecentContactsEmpty: 'No contact requests yet.',
  overviewRecentActivity: 'Recent activity',
  overviewRecentActivityEmpty: 'No recent activity.',
  overviewColMerchant: 'Merchant',
  overviewColResult: 'Result',
  overviewColTime: 'Time',

  merchantsTitle: 'Merchants',
  merchantsCountOne: 'merchant found',
  merchantsCountMany: 'merchants found',
  merchantsSearchPlaceholder: 'Search merchants by name or email…',
  merchantsColName: 'Name',
  merchantsColCategory: 'Category',
  merchantsColTier: 'Tier',
  merchantsColStatus: 'Status',
  merchantsColMonthlyPlays: 'Monthly plays',
  merchantsColUsage: 'Usage',
  merchantsColJoined: 'Joined',
  merchantsStatusActive: 'Active',
  merchantsStatusDisabled: 'Disabled',
  merchantsToggleEnable: 'Enable merchant',
  merchantsToggleDisable: 'Disable merchant',
  merchantsUsageAtLimit: 'At limit',
  merchantsEmpty: 'No merchants found.',
  merchantsErrorLoad: 'Unable to load merchants.',

  merchantDetailBack: 'Merchants',
  merchantDetailStatActive: 'Active',
  merchantDetailSlug: 'Slug',
  merchantDetailCreated: 'Created',
  merchantDetailDisabledBannerTitle: 'This merchant is disabled',
  merchantDetailDisabledBannerBody:
    'Players cannot access the game page. The merchant will see a "Game Unavailable" screen.',
  merchantDetailEnableButton: 'Enable merchant',
  merchantDetailEnabling: 'Enabling…',
  merchantDetailDisableButton: 'Disable merchant',
  merchantDetailDisabling: 'Disabling…',
  merchantDetailViewPlayerPage: 'View player page',
  merchantDetailResetPlays: 'Reset monthly plays',
  merchantDetailDelete: 'Delete merchant',
  merchantDetailFeedbackEnabled: 'Merchant enabled',
  merchantDetailFeedbackDisabled: 'Merchant disabled',
  merchantDetailFeedbackUpdateFail: 'Failed to update',
  merchantDetailFeedbackResetOk: 'plays reset for this month',
  merchantDetailFeedbackResetFail: 'Failed to reset plays',
  merchantDetailFeedbackDeleteFail: 'Failed to delete merchant',
  merchantDetailNotFound: 'Merchant not found',
  merchantDetailLoadFail: 'Failed to load merchant',
  merchantDetailResetConfirmTitle: 'Reset monthly plays',
  merchantDetailResetConfirmBody:
    'This will permanently delete all game plays for this merchant from this month. This cannot be undone.',
  merchantDetailResetConfirmButton: 'Reset plays',
  merchantDetailDeleteConfirmTitle: 'Delete merchant',
  merchantDetailDeleteConfirmBody:
    'This will permanently delete the merchant and ALL associated data (games, players, coupons, plays). This action CANNOT be undone.',
  merchantDetailDeleteConfirmButton: 'Delete forever',
  merchantDetailUsageTitle: 'Monthly usage',
  merchantDetailUsagePlaysUnit: 'plays',
  merchantDetailUsageUnlimited: 'Unlimited',
  merchantDetailUsageUnlimitedNote: 'Unlimited plan — no usage cap',
  merchantDetailUsagePercentUsed: '% of monthly limit used',
  merchantDetailStatTotalPlayers: 'Total players',
  merchantDetailStatTotalGames: 'Total games',
  merchantDetailStatActiveGames: 'Active games',
  merchantDetailStatCouponsRedeemed: 'Coupons redeemed',
  merchantDetailGamesTitle: 'Games',
  merchantDetailGamesEmpty: 'No games configured yet.',
  merchantDetailPlayersTitle: 'Players',
  merchantDetailPlayersEmpty: 'No players yet.',
  merchantDetailPlayersShowingOf: 'of',
  merchantDetailPlayersShowingSuffix: 'players shown',
  merchantDetailCouponsTitle: 'Recent coupons',
  merchantDetailCouponsEmpty: 'No coupons generated yet.',
  merchantDetailColType: 'Type',
  merchantDetailColCreated: 'Created',
  merchantDetailColLastSeen: 'Last seen',
  merchantDetailColCode: 'Code',
  merchantDetailColPrize: 'Prize',
  merchantDetailColValidUntil: 'Valid until',
  merchantDetailPlayerAnonymous: 'Anonymous',
  merchantDetailColPlays: 'Plays',
  merchantDetailColWins: 'Wins',
  merchantDetailColEmail: 'Email',

  tierChangerLabel: 'Tier:',
  tierChangerSave: 'Save',
  tierChangerConfirmChange: 'Confirm change',
  tierChangerConfirming: 'Confirming…',
  tierChangerCancel: 'Cancel',
  tierChangerConfirmPrefix: 'Are you sure? The tier will change from',
  tierChangerConfirmTo: 'to',

  contactsTitle: 'Contact requests',
  contactsErrorLoad: 'Error loading',
  contactsTotalSuffix: 'total',
  contactsColDate: 'Date',
  contactsColBusiness: 'Business',
  contactsColContact: 'Contact',
  contactsColEmail: 'Email',
  contactsColPhone: 'Phone',
  contactsColType: 'Type',
  contactsColStatus: 'Status',
  contactsEmpty: 'No contact requests yet.',
  contactsStatusNew: 'New',
  contactsStatusContacted: 'Contacted',
  contactsStatusConverted: 'Converted',
  contactsStatusRejected: 'Rejected',
  contactsMessageLabel: 'Message:',

  settingsTitle: 'Platform settings',
  settingsSubtitle: 'Configure tier limits and platform-wide settings.',
  settingsFeedbackTierSaved: 'Tier limits saved successfully',
  settingsFeedbackPlatformSaved: 'Platform settings saved successfully',
  settingsFeedbackTierFail: 'Failed to save tier limits',
  settingsFeedbackPlatformFail: 'Failed to save settings',
  settingsTierSectionTitle: 'Tier limits',
  settingsTierSectionSource: 'Source:',
  settingsTierSectionSourceDb: 'Database',
  settingsTierSectionSourceDefault: 'Default (no DB values found)',
  settingsTierSaveButton: 'Save tier limits',
  settingsTierMonthlyPlays: 'Monthly plays limit',
  settingsPlatformSectionTitle: 'Platform settings',
  settingsPlatformSectionSubtitle: 'Global configuration for the platform.',
  settingsPlatformSaveButton: 'Save platform settings',
  settingsPlatformDefaultAtmosphere: 'Default atmosphere for new merchants',
  settingsPlatformAtmosphereHelp: 'Applied to new merchants when they sign up.',
  settingsPlatformSiteName: 'Site name',
  settingsPlatformSupportEmail: 'Support email',
  settingsSourceInfoTitle: 'Database-backed configuration',
  settingsSourceInfoBody:
    'All settings are stored in the platform_settings table. Changes take effect within 30 seconds. Default values are only used if no database values exist.',

  settingsSignupSectionTitle: 'Try the app',
  settingsSignupSectionSubtitle:
    'Control whether visitors can create an account on their own.',
  settingsSignupToggleLabel: 'Public sign-up',
  settingsSignupToggleDescOn:
    'Enabled — visitors can create an account through /sign-up (email/password or Google).',
  settingsSignupToggleDescOff:
    'Disabled — /sign-up shows a contact card (WhatsApp + form). You create accounts manually.',
  settingsSignupFeedbackSaved: 'Setting saved',
  settingsSignupFeedbackFail: 'Failed to save setting',
  settingsSignupBadgeOn: 'Enabled',
  settingsSignupBadgeOff: 'Disabled',

  atmosphereJoyful: 'Joyful',
  atmosphereElegant: 'Elegant',
  atmosphereEnergetic: 'Energetic',
  atmosphereCalm: 'Calm',
  atmosphereFestive: 'Festive',
  atmosphereLuxury: 'Luxury',
  atmospherePlayful: 'Playful',
  atmosphereNeon: 'Neon',
  atmosphereCustom: 'Custom',

  tierFree: 'Free',
  tierStarter: 'Starter',
  tierPro: 'Pro',
  tierEnterprise: 'Enterprise',
}

export const ADMIN_TEXT: Record<Lang, AdminText> = { fr, en }
